#!/bin/sh

board=$1

common_init() #
{
	mkdir -p var
	echo x > var/.music_current
	chmod 666 var/.music_current
	touch var/.request.log
	chmod 666 var/.request.log
}

board_simulate_init() #
{
	common_init
	mkdir -p light
	for f in `seq 0 7`
	do
		echo 0 > light/$f
	done
	chmod 666 light/*
	mkdir -p music
	touch music/{song0.mp3,song1.mp3,song2.mp3,song3.mp3,song4.mp3}
}

board_yunuo_init() #
{
	common_init
	cp -Rf board/$board/php/* .
	cp -Rf board/$board/bin/* bin/
}

board_remote_init() #
{
	common_init
	cp -Rf board/$board/php/* .
	cd .. && make
	cp ../switcher .
	cp ../web_agent .
	cp ../board .
}

if [ x$board = "xsimulate" ]; then
	board_simulate_init
elif [ x$board = "xyunuo" ]; then
	board_yunuo_init
elif [ x$board = "xremote" ]; then
	board_remote_init
else
	echo "Usage: install <simulate|yunuo|remote>"
fi

exit 0
